version: '3.8'

services:
    storyhub_db:
        container_name: storyhub_db
        restart: always
        image: mysql:8.0.38
        environment:
            MYSQL_DATABASE: storyhub
            MYSQL_ROOT_PASSWORD: 12345678
        ports:
            - '3307:3306'
        volumes:
            - storyhub_db:/var/lib/mysql
        networks:
            - my_network

volumes:
    storyhub_db:

networks:
    my_network:
        driver: bridge
